import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  card: {
    backgroundColor: "#fff",
    margin: 15,
    padding: 15,
    borderRadius: 12,
    elevation: 2,
    marginBottom: 0,
    marginTop: 15,
  },
  cardTitle: {
    fontWeight: "bold",
    fontSize: 15,
    marginBottom: 12,
    color: "#1E293B",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  label: { color: "#64748B", fontSize: 13 },
  value: {
    color: "#1E293B",
    fontSize: 13,
    fontWeight: "500",
    maxWidth: "60%",
    textAlign: "right",
  },
  checkRow: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: "#CBD5E1",
    borderRadius: 5,
    marginRight: 10,
  },
  checkboxOn: { backgroundColor: "#F59E0B", borderColor: "#F59E0B" },
  inputLabel: {
    marginTop: 12,
    fontWeight: "600",
    color: "#334155",
    marginBottom: 4,
  },
  textArea: {
    backgroundColor: "#F8FAFC",
    padding: 10,
    borderRadius: 10,
    minHeight: 80,
    textAlignVertical: "top",
  },
  btns: {
    flexDirection: "row",
    margin: 15,
    gap: 10,
    marginTop: 20,
    marginBottom: 30,
  },
  backBtn: {
    flex: 1,
    backgroundColor: "#E2E8F0",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  backTxt: { fontWeight: "bold", color: "#475569" },
  payBtn: {
    flex: 2,
    backgroundColor: "#F59E0B",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  payTxt: { color: "#fff", fontWeight: "bold", fontSize: 15 },
});
